## 1. Import Dependencies

In [1]:
! pip install stable-baselines3[extra]

Keyring is skipped due to an exception: 'keyring.backends'


In [2]:
# pytorch for GPU acceleration
! pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Keyring is skipped due to an exception: 'keyring.backends'
Looking in indexes: https://download.pytorch.org/whl/cu118


In [5]:
! pip install gym-notebook-wrapper

Keyring is skipped due to an exception: 'keyring.backends'


In [29]:
! pip install gymnasium[accept-rom-license]

Keyring is skipped due to an exception: 'keyring.backends'


In [30]:
import gymnasium as gym
import os
import gnwrapper

from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env

## 2. Test Environment

In [31]:
environment_name = "ALE/Breakout-v5"
#env = gym.make(environment_name, render_mode='rgb_array')

In [32]:
env = gnwrapper.LoopAnimation(gym.make(environment_name, render_mode="rgb_array"))
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info, _ = env.step(action)
        score+=reward
    print(f'Episode:{episode} Score:{score}')
env.display()
env.close()

/home/alieb/anaconda3/lib/python3.7/site-packages/gymnasium/utils/passive_env_checker.py:365: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  "No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps."


Episode:1 Score:1.0
Episode:2 Score:2.0
Episode:3 Score:1.0
Episode:4 Score:0.0
Episode:5 Score:2.0


In [23]:
env.reset()

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 {'lives': 5, 'episode_frame_number': 0, 'frame_number': 3793})

In [24]:
env.action_space

Discrete(4)

In [25]:
env.observation_space

Box(0, 255, (210, 160, 3), uint8)

## 3. Vectorize Environment and Train Mode
- To vecrorize the environment and training with several different environments at once, to train the agents faster by training in parallel.

In [38]:
# use helper function(make_atari_env) from stable baselines to create wrapped atari environments
env = make_atari_env("ALE/Breakout-v5", n_envs=4, seed=0)

In [39]:
# stack the environments together
env = VecFrameStack(env, n_stack=4)

In [40]:
env.reset()

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0

In [41]:
env.render()

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [42]:
log_path = os.path.join('Training', 'ATARI', 'Logs')
model = A2C('CnnPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [44]:
model.learn(total_timesteps=500000)

Logging to Training/ATARI/Logs/A2C_2


------------------------------------
| rollout/              |          |
|    ep_len_mean        | 586      |
|    ep_rew_mean        | 12.6     |
| time/                 |          |
|    fps                | 266      |
|    iterations         | 100      |
|    time_elapsed       | 7        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -0.197   |
|    explained_variance | 0.944    |
|    learning_rate      | 0.0007   |
|    n_updates          | 3860     |
|    policy_loss        | -0.17    |
|    value_loss         | 0.146    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 584      |
|    ep_rew_mean        | 12.7     |
| time/                 |          |
|    fps                | 245      |
|    iterations         | 200      |
|    time_elapsed       | 16       |
|    total_timesteps    | 4000     |
| train/                |          |
|

## 4. Save and Reload Model

In [46]:
a2c_path = os.path.join('Training', 'ATARI', 'Saved Models', 'A2C_500k_Breakout_Model')
model.save(a2c_path)

In [47]:
del model

In [48]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.


## 5. Evaluation and Test

In [49]:
# the evaluation can not be done on multiple vectorize environments so need to vectorize it to a single env
env = make_atari_env("ALE/Breakout-v5", n_envs=1, seed=0)
env = VecFrameStack(env, n_stack=4)

In [50]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

/home/alieb/anaconda3/lib/python3.7/site-packages/gymnasium/utils/passive_env_checker.py:365: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  "No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps."


(21.7, 6.050619802962338)

In [51]:
env.close()

In [53]:
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, done, info= env.step(action)
    env.render()
env.close()

In [ ]:
env = gnwrapper.LoopAnimation(gym.make(environment_name, render_mode="rgb_array"))
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info, _ = env.step(action)
        score+=reward
    print(f'Episode:{episode} Score:{score}')
env.display()
env.close()